### ISSUE TITLE
supported peripherals?

### ISSUE THREAD

**Issue by ntn888** [ZigEmbeddedGroup/nordic-nrf5x#21]
HI, is it possible to provide a table of currently supported peripherals?
Is BLE supported?

Thanks.

**Comment by MasterQ32** [comment]
Right now, we basically have only support for registers, so the answer is "technicallly yes". No HAL is available here right now.

**Comment by ntn888** [comment]
okay thanks for the prompt feedback!

**Comment by MasterQ32** [comment]
Feel free to join the Discord Server ([link here](https://github.com/ZigEmbeddedGroup)) if you want to have a quick response time :)
